version: '3.1'
services:
    dynamock:
        command: ["-c", "/etc/config/basic.json"]
        image: helderfarias/dynamock
        ports:
            - 3010:3010
        volumes:
            - $PWD/templates:/etc/config
